### Source : https://github.com/deeplearningzerotoall/PyTorch

In [1]:
import torch
import numpy as np

In [2]:
print(torch.__version__)

1.9.0+cu102


## rank 1 numpy array

In [22]:
print("********** rank 1 - Numpy ****************")
n1 = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t1)
print("rank = ", n1.ndim) # rank
print("shape = ", n1.shape) # shape
print("dtype = ", n1.dtype) # dtype

********** rank 1 - Numpy ****************
[0. 1. 2. 3. 4. 5. 6.]
rank =  1
shape =  (7,)
dtype =  float64


## indexing and slicing

In [23]:
print(n1[0], n1[1], n1[-1])
print(n1[2:5], n1[4:-1])
print(n1[:2], n1[3:])

0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


## rank 2 numpy array : rank & shape

In [24]:
print("********** rank 2 - Numpy ****************")
n2 = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(n2)
print('rank = ', n2.ndim) # rank
print('shape = ', n2.shape) # shape
print("dtype = ", n2.dtype) # dtype

********** rank 2 - Numpy ****************
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
rank =  2
shape =  (4, 3)
dtype =  float64


## rank 1 tensor : dim(rank), size(shape) and dtype

In [25]:
print("********** rank 1 - Tensor ****************")
t1 = torch.tensor([1,2,3,4])
print(t1)
print('dim = ', t1.dim(), t1.ndim)
print('size = ', t1.shape, t1.size())
print('dtype = ', t1.dtype)

********** rank 1 - Tensor ****************
tensor([1, 2, 3, 4])
dim =  1 1
size =  torch.Size([4]) torch.Size([4])
dtype =  torch.int64


## rank 2 tensor : dim(rank), size(shape) and dtype

In [26]:
print("********** rank 2 - Tensor ****************")
t2 = torch.tensor([[1., 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(t2)
print('dim = ', t2.dim(), t2_1.ndim)
print('size = ', t2.shape, t2.size())
print('dtype = ', t2.dtype)

********** rank 2 - Tensor ****************
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
dim =  2 2
size =  torch.Size([3, 4]) torch.Size([3, 4])
dtype =  torch.float32


## tensor indexing

In [27]:
## indexing - indexing을 사용하면 항상 차원이 감소합니다
print(t2[0])
print(t2[1])
print(t2[2])
print(t2[0, 1])
print(t2[1, 2])
print(t2[2, 3])

tensor([1., 2., 3., 4.])
tensor([5., 6., 7., 8.])
tensor([ 9., 10., 11., 12.])
tensor(2.)
tensor(7.)
tensor(12.)


## tensor slicing

In [28]:
## slicing
print(t2[1:3, 1:3])
print(t2[:2, 1:3])
print(t2[1:3, 3:])

tensor([[ 6.,  7.],
        [10., 11.]])
tensor([[2., 3.],
        [6., 7.]])
tensor([[ 8.],
        [12.]])


## rank 3 tensor : dim(rank), size(shape) and dtype

In [29]:
print("********** rank 3 - Tensor ****************")
t3 = torch.tensor([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
print(t3)
print('dim = ', t3.dim(), t3.ndim)
print('size = ', t3.shape, t3.size())
print('dtype = ', t3.dtype)

********** rank 3 - Tensor ****************
tensor([[[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]],

         [[13, 14, 15, 16],
          [17, 18, 19, 20],
          [21, 22, 23, 24]]]])
dim =  4 4
size =  torch.Size([1, 2, 3, 4]) torch.Size([1, 2, 3, 4])
dtype =  torch.int64


## rank 4 tensor : rank & shape

In [30]:
print("********** rank 4 - Tensor ****************")
t4 = torch.tensor([
    [
        [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
])
print(t4)
print('dim = ', t4.dim(), t4.ndim)
print('size = ', t4.shape, t4.size())
print('dtype = ', t4.dtype)

********** rank 4 - Tensor ****************
tensor([[[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12]],

         [[13, 14, 15, 16],
          [17, 18, 19, 20],
          [21, 22, 23, 24]]]])
dim =  4 4
size =  torch.Size([1, 2, 3, 4]) torch.Size([1, 2, 3, 4])
dtype =  torch.int64


## tensor generation : ones & zeros

In [32]:
## 상수형 tensor를 생성하는 방법으로 아래와 같은 방법이 많이 사용됩니다
print(torch.ones(size=(2,2)))
print(torch.zeros(2,2))

tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])


## matrix multiplication

In [33]:
print("********** matmul ****************")
matrix1 = torch.tensor([[1., 2.], [3., 4.]])
matrix2 = torch.tensor([[1.],[2.]])
matmul = torch.matmul(matrix1, matrix2)
print(matrix1)
print(matrix2)
print(matmul)

********** matmul ****************
tensor([[1., 2.],
        [3., 4.]])
tensor([[1.],
        [2.]])
tensor([[ 5.],
        [11.]])


## matrix multiply & broadcasting

In [34]:
print("********** multiply & Broadcasting ****************")
multiply1 = matrix1*matrix2
print(multiply1)
multiply2 = torch.multiply(matrix1, matrix2)
print(multiply2)

********** multiply & Broadcasting ****************
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


#### Broadcasting 규칙

두 개의 배열을 브로드캐스팅하는 것은 다음 규칙을 따릅니다.

1. 배열의 랭크가 같지 않으면 두 모양이 같은 길이가 될 때까지 배열의 낮은 랭크쪽에 1을 붙입니다.
2. 두 배열은 차원에서 크기가 같거나 배열 중 하나의 차원에 크기가 1 인 경우 차원에서 호환 가능하다고 합니다.
3. 배열은 모든 차원에서 호환되면 함께 브로드캐스트 될 수 있습니다.
4. 브로드캐스트 후 각 배열은 두 개의 입력 배열의 요소 모양 최대 개수와 동일한 모양을 가진 것처럼 동작합니다.
5. 한 배열의 크기가 1이고 다른 배열의 크기가 1보다 큰 차원에서 첫 번째 배열은 마치 해당 차원을 따라 복사 된 것처럼 작동합니다

실제로 동작하는 방식을 생각해 봅시다.

1. A와 B의 모양을 생각합니다.
2. 두 배열이 len(A.shape) == len(B.shape)인지 확인을 합니다.
3. 같지 않은 경우에는 두 배열의 모양 길이가 같아질때까지 적은 쪽의 shape 앞에 1 을 추가해 줍니다.
- 예: (5,3)–>(1,5,3)
4. shape이 1인 곳은 복사가 됩니다.
- 예: shape의 변화는 아래와 같게 될겁니다.
- (5, 3)+(3,)
- (5, 3)+(1, 3)
- (5, 3) + (5, 3)
- (5, 3)

## matrix addition

In [35]:
print("********** Add ****************")
matrix1 = torch.tensor([[3., 3.]])
matrix2 = torch.tensor([[2., 2.]])
matadd2 = matrix1+matrix2
print(matadd2)

********** Add ****************
tensor([[5., 5.]])


## matrix addition & broadcasting

In [36]:
print("********** Add & Broadcasting ****************")
# Broadcasting
matrix1 = torch.tensor([[3., 3.]])
matrix2 = torch.tensor([[2.],[2.]])
matadd1 = matrix1+matrix2
print(matadd1)

********** Add & Broadcasting ****************
tensor([[5., 5.],
        [5., 5.]])


## arange

In [37]:
print("********** range ****************")
start=3
end=18
steps=3
print(torch.arange(start, end, steps))

start=3
end=1
steps=-0.5
print(torch.arange(start, end, steps))

end=5
print(torch.arange(end))

********** range ****************
tensor([ 3,  6,  9, 12, 15])
tensor([3.0000, 2.5000, 2.0000, 1.5000])
tensor([0, 1, 2, 3, 4])


## random number generation : Gaussian & uniform distribution

In [38]:
print("********** random number generation ****************")

print(torch.randn([3]).numpy())
print(torch.rand([2]))
print(torch.rand([2, 3]))

********** random number generation ****************
[-1.2626133  -0.8260956   0.73928463]
tensor([0.9332, 0.6394])
tensor([[0.1099, 0.6661, 0.4891],
        [0.0578, 0.8697, 0.1183]])


## reduce mean/sum & dim

In [40]:
print("********** reduce mean & axis ****************")

x = torch.tensor([[1., 2.],
                 [3., 4.]])

print(torch.mean(x))
print(torch.mean(x, dim=0)) 
print(torch.mean(x, dim=1)) 
print(torch.mean(x, dim=-1))
print(torch.mean(torch.mean(x, dim=-1)))

********** reduce mean & axis ****************
tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])
tensor(2.5000)


여기서 축(dim)은 각 배열의 차원에 해당되는 인덱스입니다. 위의 예를 설명하면

- x.shape 은 (2, 2) 입니다.
- torch.mean(x, dim=0) 은
- x.shape[axis]: x.shape[0] 에 대하여 연산을 하라는 의미
입니다.

X.shape == (5, 3, 2) 인 경우를 생각해봅시다. 이 경우 torch.mean(X, dim=1) 의 결과값은

1. X.shape[axis] => X.shape[1] 에 대해서 연산을 하기 때문에
2. torch.mean(X, axis=1).shape 은 (5, 3, 2) -> (5, 2) 가 됩니다.

In [41]:
print(torch.sum(x))
print(torch.sum(x, dim=0))
print(torch.sum(x, dim=-1))
print(torch.mean(torch.sum(x, dim=-1)))

tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor(5.)


## argmax/max

In [44]:
x =torch.tensor([[0, 1, 2],
                 [2, 1, 0]])
print(torch.argmax(x, dim=0))
print(torch.argmax(x, dim=1))
print(torch.argmax(x, dim=-1))

print(torch.max(x, dim=0))
print(torch.max(x, dim=1))
print(torch.max(x, dim=-1))

tensor([1, 0, 0])
tensor([2, 0])
tensor([2, 0])
torch.return_types.max(
values=tensor([2, 1, 2]),
indices=tensor([1, 0, 0]))
torch.return_types.max(
values=tensor([2, 2]),
indices=tensor([2, 0]))
torch.return_types.max(
values=tensor([2, 2]),
indices=tensor([2, 0]))


## view/reshape

In [47]:
print("********** Reshape ****************")
# reshape

t=torch.tensor([[[0, 1, 2],[3, 4, 5]], [[6, 7, 8],[9, 10, 11]]])
print(t.size())

t=torch.tensor([[[0, 1, 2],[3, 4, 5]], [[6, 7, 8],[9, 10, 11]]])
print(t.size())

print(t.view(-1))
print(t.view(-1, 2))
print(t.view(-1, 3))
print(t.view(-1, 1, 3))

print(torch.reshape(t, shape=[-1]))
print(torch.reshape(t, shape=[-1, 2]))
print(torch.reshape(t, shape=[-1, 3]))
print(torch.reshape(t, shape=[-1, 1, 3]))

********** Reshape ****************
torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
tensor([[[ 0,  1,  2]],

        [[ 3,  4,  5]],

        [[ 6,  7,  8]],

        [[ 9, 10, 11]]])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
tensor([[[ 0,  1,  2]],

        [[ 3,  4,  5]],

        [[ 6,  7,  8]],

        [[ 9, 10, 11]]])


## squeeze and unsqueeze

In [53]:
x=torch.tensor([[0],[1],[2]])

print(x.shape)
print(x)
x1 = torch.squeeze(x)
print(x1.shape)
print(x1)


y=torch.tensor([0,1,2])

print(y.shape)
print(y)
y1 = torch.unsqueeze(y, 1)
print(y1.shape)
print(y1)

torch.Size([3, 1])
tensor([[0],
        [1],
        [2]])
torch.Size([3])
tensor([0, 1, 2])
torch.Size([3])
tensor([0, 1, 2])
torch.Size([3, 1])
tensor([[0],
        [1],
        [2]])


## one-hot encoding

In [51]:
print("********** One hot ****************")

x = torch.LongTensor([[0], [1], [2], [0]])
print(x)

one_hot = torch.zeros(4, 3) # batch_size = 4, classes = 3
one_hot.scatter_(1, x, 1)

print(one_hot, type(one_hot))

********** One hot ****************
tensor([[0],
        [1],
        [2],
        [0]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]]) <class 'torch.Tensor'>


## type casting

In [54]:
print("********** Casting ****************")

lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

print(lt.float())

bt = torch.ByteTensor([True, False, False, True])
print(bt)

print(bt.long())
print(bt.float())

********** Casting ****************
tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])
tensor([1, 0, 0, 1], dtype=torch.uint8)
tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### Concatenation

In [55]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


## stack

In [56]:
print("********** Stack ****************")

x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim=1))

print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

********** Stack ****************
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


## Ones and Zeros like

In [57]:
print("********** Ones and Zeros like ****************")

x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

print(torch.ones_like(x))
print(torch.zeros_like(x))

********** Ones and Zeros like ****************
tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### In-place operation

In [ ]:
x = torch.FloatTensor([[1, 2], [3, 4]])

print(x.mul(2.))
print(x)
print(x.mul_(2.))
print(x)

## zips

In [58]:
print("********** Zips ****************")

for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

********** Zips ****************
1 4
2 5
3 6
1 4 7
2 5 8
3 6 9
