In [ ]:
import torch 
import numpy as np

## 파이썬 List 정의 : rank 0 - 4

In [ ]:
L0=3.
L1=[1.,2.,3.]
L2 = [[1., 2., 3.], [4., 5., 6.]] 
L3 = [[[1., 2., 3.], [4., 5., 6.]], [[7., 8., 9.], [10., 11., 12.]]] 
L4 = [[[[1., 2],[3., 4.]], [[5., 6.],[7., 8]]], 
      [[[9., 10],[11., 12.]], [[13., 14.],[15., 16]]]]

In [ ]:
print(type(L0), L0)
print(type(L1), L1)
print(type(L2), L2)
print(type(L3), L3)
print(type(L4), L4)

<class 'float'> 3.0
<class 'list'> [1.0, 2.0, 3.0]
<class 'list'> [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]
<class 'list'> [[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], [[7.0, 8.0, 9.0], [10.0, 11.0, 12.0]]]
<class 'list'> [[[[1.0, 2], [3.0, 4.0]], [[5.0, 6.0], [7.0, 8]]], [[[9.0, 10], [11.0, 12.0]], [[13.0, 14.0], [15.0, 16]]]]


## List을 Numpy array로 변환

In [ ]:
N0 = np.array(L0)
N1 = np.array(L1)
N2 = np.array(L2)
N3 = np.array(L3)
N4 = np.array(L4)

In [ ]:
print(type(N0), N0)
print(type(N1), N1)
print(type(N2), N2)
print(type(N3), N3)
print(type(N4), N4)

<class 'numpy.ndarray'> 3.0
<class 'numpy.ndarray'> [1. 2. 3.]
<class 'numpy.ndarray'> [[1. 2. 3.]
 [4. 5. 6.]]
<class 'numpy.ndarray'> [[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
<class 'numpy.ndarray'> [[[[ 1.  2.]
   [ 3.  4.]]

  [[ 5.  6.]
   [ 7.  8.]]]


 [[[ 9. 10.]
   [11. 12.]]

  [[13. 14.]
   [15. 16.]]]]


## numpy dim (rank)

In [ ]:
print('---------- Numpy dim -----------------')
print(N0.ndim)
print(N1.ndim)
print(N2.ndim)
print(N3.ndim)
print(N4.ndim)

---------- Numpy dim -----------------
0
1
2
3
4


## numpy shape

In [ ]:
print('---------- Numpy shape ---------------')
print(N0.shape)
print(N1.shape)
print(N2.shape)
print(N3.shape)
print(N4.shape)

---------- Numpy shape ---------------
()
(3,)
(2, 3)
(2, 2, 3)
(2, 2, 2, 2)


## numpy array을 pytorch의 tensor로 변환

In [ ]:
T0 = torch.tensor(N0)
T1 = torch.tensor(N1)
T2 = torch.tensor(N2)
T3 = torch.tensor(N3)
T4 = torch.tensor(N4)

## tensor 출력 : 값, shape, dtype

In [ ]:
print("---------- Pytorch -------------")
print(T0)
print(T1)
print(T2)
print(T3)
print(T4)
print()

---------- Pytorch -------------
tensor(3., dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float64)
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]], dtype=torch.float64)
tensor([[[[ 1.,  2.],
          [ 3.,  4.]],

         [[ 5.,  6.],
          [ 7.,  8.]]],


        [[[ 9., 10.],
          [11., 12.]],

         [[13., 14.],
          [15., 16.]]]], dtype=torch.float64)



## Pytorch dim 출력

In [ ]:
print("---------- Pytorch dim -------------")
print(T0.dim())
print(T1.dim())
print(T2.dim())
print(T3.dim())
print(T4.dim())
print()

---------- Pytorch dim -------------
0
1
2
3
4



## tensor size 출력

In [ ]:
print("---------- Pytorch size -------------")
print(T0.size(),T0.dtype)
print(T1.size(),T1.dtype)
print(T2.size(),T2.dtype)
print(T3.size(),T3.dtype)
print(T4.size(),T4.dtype)

---------- Pytorch size -------------
torch.Size([]) torch.float64
torch.Size([3]) torch.float64
torch.Size([2, 3]) torch.float64
torch.Size([2, 2, 3]) torch.float64
torch.Size([2, 2, 2, 2]) torch.float64


## tensor를 numpy array로 변환

In [ ]:
print("------------- pytorch -> Numpy -------------")
print(type(T2.numpy()), T2.numpy(), np.array(T2))
print(type(T4.numpy()), T4.numpy(), np.array(T4))
print((T2+T2).numpy())

------------- pytorch -> Numpy -------------
<class 'numpy.ndarray'> [[1. 2. 3.]
 [4. 5. 6.]] [[1. 2. 3.]
 [4. 5. 6.]]
<class 'numpy.ndarray'> [[[[ 1.  2.]
   [ 3.  4.]]

  [[ 5.  6.]
   [ 7.  8.]]]


 [[[ 9. 10.]
   [11. 12.]]

  [[13. 14.]
   [15. 16.]]]] [[[[ 1.  2.]
   [ 3.  4.]]

  [[ 5.  6.]
   [ 7.  8.]]]


 [[[ 9. 10.]
   [11. 12.]]

  [[13. 14.]
   [15. 16.]]]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]]


## numpy array를 tensor로 변환

In [ ]:
print("------------- Numpy -> pytorch -------------")
print(type(torch.tensor(N2)), torch.tensor(N2))
print(type(torch.from_numpy(N4)), torch.tensor(N4))
print(torch.add(T2, T2))

------------- Numpy -> pytorch -------------
<class 'torch.Tensor'> tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
<class 'torch.Tensor'> tensor([[[[ 1.,  2.],
          [ 3.,  4.]],

         [[ 5.,  6.],
          [ 7.,  8.]]],


        [[[ 9., 10.],
          [11., 12.]],

         [[13., 14.],
          [15., 16.]]]], dtype=torch.float64)
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]], dtype=torch.float64)
