In [1]:
import torch
import numpy as np

In [2]:
print(torch.__version__)

1.9.0+cu102


In [3]:
torch.cuda.is_available()

False

In [4]:
x = torch.rand(2,3)
print(x)

tensor([[0.2043, 0.5772, 0.0771],
        [0.8552, 0.1527, 0.4478]])


In [5]:
x = torch.tensor([2.])
m=torch.matmul(x,x)

In [6]:
print("hello,{}".format(m))
print("m:",m.numpy())

hello,4.0
m: 4.0


In [7]:
a=np.array([[1,2],[3,4]])
b=torch.from_numpy(a)
print(b)

tensor([[1, 2],
        [3, 4]])


In [8]:
c=torch.tensor(1)
print(b+c)

tensor([[2, 3],
        [4, 5]])


## 함수 정의

In [9]:
def fizzbuzz(max_num):
    counter=torch.tensor(0)
    max_num= torch.tensor(max_num)
    for num in range(1,max_num.numpy()+1):
        num = torch.tensor(num)
        if int(num % 3) == 0 and int(num % 5) == 0:
            print('3과 5의 배수')
        elif int(num % 3) == 0:
            print('3의 배수')
        elif int(num % 5) == 0:
            print('5의 배수')
        else:
            print(num.numpy())
        counter += 1

## 함수 실행

In [10]:
fizzbuzz(15)

1
2
3의 배수
4
5의 배수
3의 배수
7
8
3의 배수
5의 배수
11
3의 배수
13
14
3과 5의 배수


## gradient 계산

In [11]:
print('Computing gradients')
W=torch.tensor([1.0],requires_grad=True)
Y=W*W
Y.backward()
print(W.grad)

Computing gradients
tensor([2.])
