In [2]:
import tensorflow as tf

## constant : string tensor 정의

In [3]:
hello = tf.constant("Hello, TensorFlow!")
print(hello)

tf.Tensor(b'Hello, TensorFlow!', shape=(), dtype=string)


## constant :float32 tensor 정의 및 tensor 덧셈

In [4]:
node1 = tf.constant(3., tf.float32)
node2 = tf.constant([4., 5., 6.]) # also tf.float32 implicitly
node3 = tf.add(node1, node2)

In [5]:
print("node1:", node1, "node2:", node2)
print("node3: ", node3)

node1: tf.Tensor(3.0, shape=(), dtype=float32) node2: tf.Tensor([4. 5. 6.], shape=(3,), dtype=float32)
node3:  tf.Tensor([7. 8. 9.], shape=(3,), dtype=float32)


## Variable tensor 정의 : rank 0 - 3

In [6]:
# tensor variable 
t0 = tf.Variable(42.) 
t1 = tf.Variable([1.,-1.])
t2 = tf.Variable([[1.,-1.],[-1., 2.]])
t3 = tf.Variable([[[0., 1., 2.],[3., 4., 5.]],[[6., 7., 8.],[9., 10., 11.]]]) 

In [7]:
print(t0)
print(t1)
print(t2)
print(t3)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=42.0>
<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([ 1., -1.], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 1., -1.],
       [-1.,  2.]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=float32, numpy=
array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.]],

       [[ 6.,  7.,  8.],
        [ 9., 10., 11.]]], dtype=float32)>


## Variable tensor rank 및 shape 출력

In [8]:
print(tf.rank(t0).numpy(), t0.shape)
print(tf.rank(t1).numpy(), t1.shape)
print(tf.rank(t2).numpy(), t2.shape)
print(tf.rank(t3).numpy(), t3.shape)

0 ()
1 (2,)
2 (2, 2)
3 (2, 2, 3)


## Variable tensor 덧셈 : broadcasting

In [9]:
x0 = tf.add(t0, 1)
x1 = tf.add(t1, 1.0)
x2 = tf.add(t2, t1)

In [10]:
print(x0)
print(x1)
print(x2)

tf.Tensor(43.0, shape=(), dtype=float32)
tf.Tensor([2. 0.], shape=(2,), dtype=float32)
tf.Tensor(
[[ 2. -2.]
 [ 0.  1.]], shape=(2, 2), dtype=float32)
