In [14]:
import tensorflow as tf
import numpy as np

## Python List 정의 : rank 0 - 4

In [15]:
L0 = 3. # a rank 0 tensor; this is a scalar with shape []
L1 = [1. ,2., 3.] # a rank 1 tensor; this is a vector with shape [3]
L2 = [[1., 2., 3.], [4., 5., 6.]] # a rank 2 tensor; a matrix with shape [2, 3]
L3 = [[[1., 2., 3.], [4., 5., 6.]], [[7., 8., 9.], [10., 11., 12.]]] # a rank 3 tensor with shape [2, 1, 3]
L4 = [[[[1., 2],[3., 4.]], [[5., 6.],[7., 8]]], 
      [[[9., 10],[11., 12.]], [[13., 14.],[15., 16]]]]

In [16]:
print(type(L0), L0)
print(type(L1), L1)
print(type(L2), L2)
print(type(L3), L3)
print(type(L4), L4)

<class 'float'> 3.0
<class 'list'> [1.0, 2.0, 3.0]
<class 'list'> [[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]]
<class 'list'> [[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], [[7.0, 8.0, 9.0], [10.0, 11.0, 12.0]]]
<class 'list'> [[[[1.0, 2], [3.0, 4.0]], [[5.0, 6.0], [7.0, 8]]], [[[9.0, 10], [11.0, 12.0]], [[13.0, 14.0], [15.0, 16]]]]


## List을 Numpy array로 변환

In [17]:
N0 = np.array(L0)
N1 = np.array(L1)
N2 = np.array(L2)
N3 = np.array(L3)
N4 = np.array(L4)

In [18]:
print(type(N0), N0)
print(type(N1), N1)
print(type(N2), N2)
print(type(N3), N3)
print(type(N4), N4)

<class 'numpy.ndarray'> 3.0
<class 'numpy.ndarray'> [1. 2. 3.]
<class 'numpy.ndarray'> [[1. 2. 3.]
 [4. 5. 6.]]
<class 'numpy.ndarray'> [[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
<class 'numpy.ndarray'> [[[[ 1.  2.]
   [ 3.  4.]]

  [[ 5.  6.]
   [ 7.  8.]]]


 [[[ 9. 10.]
   [11. 12.]]

  [[13. 14.]
   [15. 16.]]]]


## Numpy dim (rank)

In [19]:
print('---------- Numpy dim -----------------')
print(N0.ndim)
print(N1.ndim)
print(N2.ndim)
print(N3.ndim)
print(N4.ndim)

---------- Numpy dim -----------------
0
1
2
3
4


## Numpy shape

In [20]:
print('---------- Numpy shape ---------------')
print(N0.shape)
print(N1.shape)
print(N2.shape)
print(N3.shape)
print(N4.shape)

---------- Numpy shape ---------------
()
(3,)
(2, 3)
(2, 2, 3)
(2, 2, 2, 2)


## Numpy array을 tensorflow의 tensor로 변환

In [21]:
# Tensorflow
T0 = tf.constant(N0)
T1 = tf.constant(N1)
T2 = tf.constant(N2)
T3 = tf.constant(N3)
T4 = tf.constant(N4)

## tensor 출력 : 값, shape, dtype

In [22]:
print("---------- Tensorflow -------------")
print(T0)
print(T1)
print(T2)
print(T3)
print(T4)
print()

---------- Tensorflow -------------
tf.Tensor(3.0, shape=(), dtype=float64)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float64)
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float64)
tf.Tensor(
[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]], shape=(2, 2, 3), dtype=float64)
tf.Tensor(
[[[[ 1.  2.]
   [ 3.  4.]]

  [[ 5.  6.]
   [ 7.  8.]]]


 [[[ 9. 10.]
   [11. 12.]]

  [[13. 14.]
   [15. 16.]]]], shape=(2, 2, 2, 2), dtype=float64)



## tensor rank 출력

In [23]:
print("---------- Tensorflow rank -------------")
print(tf.rank(T0), tf.rank(T0).numpy())
print(tf.rank(T1), tf.rank(T1).numpy())
print(tf.rank(T2), tf.rank(T2).numpy())
print(tf.rank(T3), tf.rank(T3).numpy())
print(tf.rank(T4), tf.rank(T4).numpy())
print()

---------- Tensorflow rank -------------
tf.Tensor(0, shape=(), dtype=int32) 0
tf.Tensor(1, shape=(), dtype=int32) 1
tf.Tensor(2, shape=(), dtype=int32) 2
tf.Tensor(3, shape=(), dtype=int32) 3
tf.Tensor(4, shape=(), dtype=int32) 4



## tensor shape 출력

In [24]:
print("---------- Tensorflow shape -------------")
print(T0.shape, tf.shape(T0), tf.shape(T0).numpy())
print(T1.shape, tf.shape(T1), tf.shape(T1).numpy())
print(T2.shape, tf.shape(T2), tf.shape(T2).numpy())
print(T3.shape, tf.shape(T3), tf.shape(T3).numpy())
print(T4.shape, tf.shape(T4), tf.shape(T4).numpy())

---------- Tensorflow shape -------------
() tf.Tensor([], shape=(0,), dtype=int32) []
(3,) tf.Tensor([3], shape=(1,), dtype=int32) [3]
(2, 3) tf.Tensor([2 3], shape=(2,), dtype=int32) [2 3]
(2, 2, 3) tf.Tensor([2 2 3], shape=(3,), dtype=int32) [2 2 3]
(2, 2, 2, 2) tf.Tensor([2 2 2 2], shape=(4,), dtype=int32) [2 2 2 2]


## tensor를 Numpy array로 변환

In [25]:
print("------------- Tensorflow -> Numpy -------------")
print(type(T2.numpy()), T2.numpy(), np.array(T2))
print(type(T4.numpy()), T4.numpy(), np.array(T4))
print((T2+T2).numpy())

------------- Tensorflow -> Numpy -------------
<class 'numpy.ndarray'> [[1. 2. 3.]
 [4. 5. 6.]] [[1. 2. 3.]
 [4. 5. 6.]]
<class 'numpy.ndarray'> [[[[ 1.  2.]
   [ 3.  4.]]

  [[ 5.  6.]
   [ 7.  8.]]]


 [[[ 9. 10.]
   [11. 12.]]

  [[13. 14.]
   [15. 16.]]]] [[[[ 1.  2.]
   [ 3.  4.]]

  [[ 5.  6.]
   [ 7.  8.]]]


 [[[ 9. 10.]
   [11. 12.]]

  [[13. 14.]
   [15. 16.]]]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]]


## Numpy array를 tensor로 변환

In [26]:
print("------------- Numpy -> Tensorflow -------------")
print(type(tf.convert_to_tensor(N2)), tf.convert_to_tensor(N2))
print(type(tf.convert_to_tensor(N4)), tf.convert_to_tensor(N4))
print(tf.add(T2, T2))

------------- Numpy -> Tensorflow -------------
<class 'tensorflow.python.framework.ops.EagerTensor'> tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float64)
<class 'tensorflow.python.framework.ops.EagerTensor'> tf.Tensor(
[[[[ 1.  2.]
   [ 3.  4.]]

  [[ 5.  6.]
   [ 7.  8.]]]


 [[[ 9. 10.]
   [11. 12.]]

  [[13. 14.]
   [15. 16.]]]], shape=(2, 2, 2, 2), dtype=float64)
tf.Tensor(
[[ 2.  4.  6.]
 [ 8. 10. 12.]], shape=(2, 3), dtype=float64)
