## tf.data를 이용하여 Dataset 만들기
#### TensorFlow를 이용하여 deep learning model을 학습할 때, input data 및 label을 공급해주기 위하여 tf.data.Dataset을 이용합니다.

In [ ]:
import tensorflow as tf

### 0에서 9까지 정수가 input data라고 가정해봅시다

In [ ]:
a = tf.range(10)
print(a)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


### dataset은 아래와 같이 만들 수 있습니다

In [ ]:
ds_tensors = tf.data.Dataset.from_tensor_slices(a)
print(ds_tensors)

<TensorSliceDataset shapes: (), types: tf.int32>


### dataset에서 한개씩 data를 꺼내서 확인해보겠습니다

In [ ]:
for x in ds_tensors:
    print (x)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


### dataset에서 앞 5개 data를 꺼내서 확인해보겠습니다

In [ ]:
data = ds_tensors.take(5)
for x in data:
    print (x)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


### dataset을 3번 반복하고 여기서 5개씩 꺼낸다.

In [ ]:
data = ds_tensors.repeat(3).batch(5)
for x in data:
    print (x)

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
tf.Tensor([5 6 7 8 9], shape=(5,), dtype=int32)
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
tf.Tensor([5 6 7 8 9], shape=(5,), dtype=int32)
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
tf.Tensor([5 6 7 8 9], shape=(5,), dtype=int32)


### dataset 내의 각 data에 함수를 적용하기 위해서는 아래와 같이 map을 사용합니다
### 이는 data 전처리에 많이 사용됩니다. 또한 data를 섞어주는 shuffle과 batch size만큼 data를 꺼내주는 batch도 사용할 수 있습니다
### 실제 data를 꺼내서 사용할 때는 아래와 같이 for문에 dataset을 넣어주면 됩니다.

In [ ]:
ds_tensors = ds_tensors.map(tf.square).shuffle(20).batch(2)
print('Elements of ds_tensors:')
for _ in range(3):
    for x in ds_tensors:
        print(x)

Elements of ds_tensors:
tf.Tensor([ 9 64], shape=(2,), dtype=int32)
tf.Tensor([4 1], shape=(2,), dtype=int32)
tf.Tensor([16 36], shape=(2,), dtype=int32)
tf.Tensor([ 0 49], shape=(2,), dtype=int32)
tf.Tensor([81 25], shape=(2,), dtype=int32)
tf.Tensor([36 49], shape=(2,), dtype=int32)
tf.Tensor([ 4 81], shape=(2,), dtype=int32)
tf.Tensor([ 1 25], shape=(2,), dtype=int32)
tf.Tensor([64 16], shape=(2,), dtype=int32)
tf.Tensor([9 0], shape=(2,), dtype=int32)
tf.Tensor([ 1 81], shape=(2,), dtype=int32)
tf.Tensor([16 25], shape=(2,), dtype=int32)
tf.Tensor([36  9], shape=(2,), dtype=int32)
tf.Tensor([49  0], shape=(2,), dtype=int32)
tf.Tensor([ 4 64], shape=(2,), dtype=int32)
