In [2]:
import tensorflow as tf

### Tensorflow & Keras version

In [3]:
print(tf.__version__)
print(tf.keras.__version__)

2.4.0-rc0
2.4.0


In [4]:
x = [[2.]]
m = tf.matmul(x, x)

In [5]:
print("hello, {}".format(m)) 
print("m:", m.numpy())

hello, [[4.]]
m: [[4.]]


In [9]:
a = tf.constant([[1,2],[3,4]])

In [10]:
print(a) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [11]:
b = tf.add(a, 1)

In [12]:
print(b) 
print()

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)



## 함수 정의

In [13]:
def fizzbuzz(max_num):
  counter = tf.constant(0)
  max_num = tf.convert_to_tensor(max_num)
  for num in range(1, max_num.numpy()+1):
    num = tf.constant(num)
    if int(num % 3) == 0 and int(num % 5) == 0:
      print('3과 5의 배수')
    elif int(num % 3) == 0:
      print('3의 배수')
    elif int(num % 5) == 0:
      print('5의 배수')
    else:
      print(num.numpy())
    counter += 1

## 함수 실행

In [14]:
fizzbuzz(15)

1
2
3의 배수
4
5의 배수
3의 배수
7
8
3의 배수
5의 배수
11
3의 배수
13
14
3과 5의 배수


## gradient 계산

In [15]:
print('Computing gradients')
W = tf.Variable([[1.0]])
with tf.GradientTape() as tape:
  loss = W * W

grad = tape.gradient(loss, W)
print(grad)  # => tf.Tensor([[ 2.]], shape=(1, 1), dtype=float32)

Computing gradients
tf.Tensor([[2.]], shape=(1, 1), dtype=float32)
