In [2]:
import tensorflow as tf
import numpy as np
from tensorflow import keras

In [44]:
## TensorFlow와 Keras의 version을 확인해봅시다
print(tf.__version__)
print(keras.__version__)

2.0.0
2.2.4-tf


## rank 1 numpy array

In [9]:
print("********** rank 1 - Numpy ****************")
t1 = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t1)
print("rank = ", t1.ndim) # rank
print("shape = ", t1.shape) # shape

********** rank 1 - Numpy ****************
[0. 1. 2. 3. 4. 5. 6.]
rank =  1
shape =  (7,)


## indexing and slicing

In [10]:
print(t1[0], t1[1], t1[-1])
print(t1[2:5], t1[4:-1])
print(t1[:2], t1[3:])

0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


## rank 2 numpy array : rank & shape

In [7]:
print("********** rank 2 - Numpy ****************")
t2 = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t2)
print('rank = ', t2.ndim) # rank
print('shape = ', t2.shape) # shape

********** rank 2 - Numpy ****************
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
rank =  2
shape =  (4, 3)


## rank 1 tensor : rank & shape

In [11]:
print("********** rank 1 - Tensor ****************")
t1_1 = tf.constant([1,2,3,4])
print(t1_1)
print('rank = ', tf.rank(t1_1).numpy())
print('shape = ', t1_1.shape)

********** rank 1 - Tensor ****************
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
rank =  1
shape =  (4,)



## rank 2 tensor : rank & shape

In [15]:
print("********** rank 2 - Tensor ****************")
t2_1 = tf.constant([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(t2_1)
print('rank = ', tf.rank(t2_1).numpy())
print('shape = ', t2_1.shape)

********** rank 2 - Tensor ****************
tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)
rank =  2
shape =  (3, 4)


## tensor indexing

In [16]:
## indexing - indexing을 사용하면 항상 차원이 감소합니다
print(t2_1[0])
print(t2_1[1])
print(t2_1[2])
print(t2_1[0, 1])
print(t2_1[1, 2])
print(t2_1[2, 3])

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)
tf.Tensor([ 9 10 11 12], shape=(4,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)


## tensor slicing

In [18]:
## slicing
print(t2_1[1:3, 1:3])
print(t2_1[:2, 1:3])
print(t2_1[1:3, 3:])

tf.Tensor(
[[ 6  7]
 [10 11]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 3]
 [6 7]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 8]
 [12]], shape=(2, 1), dtype=int32)


## rank 3 tensor : rank & shape

In [9]:
print("********** rank 3 - Tensor ****************")
t3 = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
print(t3)
print('rank = ', tf.rank(t3).numpy())
print('shape = ', t3.shape)

********** rank 3 - Tensor ****************
tf.Tensor(
[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]]], shape=(1, 2, 3, 4), dtype=int32)
rank =  4
shape =  (1, 2, 3, 4)



## rank 4 tensor : rank & shape

In [14]:
print("********** rank 4 - Tensor ****************")
t4 = tf.constant([
    [
        [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
])
print(t4)
print('rank = ', tf.rank(t4).numpy())
print('shape = ', t4.shape)

********** rank 4 - Tensor ****************
tf.Tensor(
[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [ 9 10 11 12]]

  [[13 14 15 16]
   [17 18 19 20]
   [21 22 23 24]]]], shape=(1, 2, 3, 4), dtype=int32)
rank =  4
shape =  (1, 2, 3, 4)


## tensor generation : ones & zeros

In [45]:
## 상수형 tensor를 생성하는 방법으로 아래와 같은 방법이 많이 사용됩니다
print(tf.ones(shape=(2,2)))
print(tf.zeros(shape=(2,2)))

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]], shape=(2, 2), dtype=float32)


## matrix multiplication

In [23]:
print("********** matmul ****************")
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[1.],[2.]])
matmul = tf.matmul(matrix1, matrix2)
print(matrix1)
print(matrix2)
print(matmul)

********** matmul ****************
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1.]
 [2.]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[ 5.]
 [11.]], shape=(2, 1), dtype=float32)


## matrix multiply & broadcasting

In [24]:
print("********** multiply & Broadcasting ****************")
multiply1 = matrix1*matrix2
print(multiply1)
multiply2 = tf.multiply(matrix1, matrix2)
print(multiply2)

********** multiply & Broadcasting ****************
tf.Tensor(
[[1. 2.]
 [6. 8.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1. 2.]
 [6. 8.]], shape=(2, 2), dtype=float32)


#### Broadcasting 규칙

두 개의 배열을 브로드캐스팅하는 것은 다음 규칙을 따릅니다.

1. 배열의 랭크가 같지 않으면 두 모양이 같은 길이가 될 때까지 배열의 낮은 랭크쪽에 1을 붙입니다.
2. 두 배열은 차원에서 크기가 같거나 배열 중 하나의 차원에 크기가 1 인 경우 차원에서 호환 가능하다고 합니다.
3. 배열은 모든 차원에서 호환되면 함께 브로드캐스트 될 수 있습니다.
4. 브로드캐스트 후 각 배열은 두 개의 입력 배열의 요소 모양 최대 개수와 동일한 모양을 가진 것처럼 동작합니다.
5. 한 배열의 크기가 1이고 다른 배열의 크기가 1보다 큰 차원에서 첫 번째 배열은 마치 해당 차원을 따라 복사 된 것처럼 작동합니다

실제로 동작하는 방식을 생각해 봅시다.

1. A와 B의 모양을 생각합니다.
2. 두 배열이 len(A.shape) == len(B.shape)인지 확인을 합니다.
3. 같지 않은 경우에는 두 배열의 모양 길이가 같아질때까지 적은 쪽의 shape 앞에 1 을 추가해 줍니다.
- 예: (5,3)–>(1,5,3)
4. shape이 1인 곳은 복사가 됩니다.
- 예: shape의 변화는 아래와 같게 될겁니다.
- (5, 3)+(3,)
- (5, 3)+(1, 3)
- (5, 3) + (5, 3)
- (5, 3)

## matrix addition

In [25]:
print("********** Add ****************")
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
matadd2 = matrix1+matrix2
print(matadd2)

********** Add ****************
tf.Tensor([[5. 5.]], shape=(1, 2), dtype=float32)


## matrix addition & broadcasting

In [26]:
print("********** Add & Broadcasting ****************")
# Broadcasting
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
matadd1 = matrix1+matrix2
print(matadd1)

********** Add & Broadcasting ****************
tf.Tensor(
[[5. 5.]
 [5. 5.]], shape=(2, 2), dtype=float32)


## range

In [30]:
print("********** range ****************")
start=3
limit=18
steps=3
print(tf.range(start, limit, steps)) # [3, 6, 9, 12, 15]

start=3
limit=1
steps=-0.5
print(tf.range(start, limit, steps)) # [3, 2.5, 2, 1.5]

limit=5
print(tf.range(limit)) # [0, 1, 2, 3, 4]

********** range ****************
tf.Tensor([ 3  6  9 12 15], shape=(5,), dtype=int32)
tf.Tensor([3.  2.5 2.  1.5], shape=(4,), dtype=float32)
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)


## random number generation : Gaussian & uniform distribution

In [31]:
print("********** random number generation ****************")
#%%

print(tf.random.normal([3]).numpy())
print(tf.random.uniform([2]))
print(tf.random.uniform([2, 3]))

********** random number generation ****************
[-2.0582135  -0.58706146  1.5852553 ]
tf.Tensor([0.24344611 0.8562622 ], shape=(2,), dtype=float32)
tf.Tensor(
[[0.58736074 0.0210669  0.84322035]
 [0.32359016 0.43640697 0.81725156]], shape=(2, 3), dtype=float32)


## reduce mean/sum & axis

In [53]:
print("********** reduce mean & axis ****************")

x = [[1., 2.],
     [3., 4.]]

print(tf.reduce_mean(x))
print(tf.reduce_mean(x, axis=0)) # axis=0으로 reduce mean
print(tf.reduce_mean(x, axis=1)) # axis=1로 reduce mean
print(tf.reduce_mean(x, axis=-1))
print(tf.reduce_mean(tf.reduce_mean(x, axis=-1)))

********** reduce mean & axis ****************
tf.Tensor(2.5, shape=(), dtype=float32)
tf.Tensor([2. 3.], shape=(2,), dtype=float32)
tf.Tensor([1.5 3.5], shape=(2,), dtype=float32)
tf.Tensor([1.5 3.5], shape=(2,), dtype=float32)
tf.Tensor(2.5, shape=(), dtype=float32)


여기서 축(axis)은 각 배열의 차원에 해당되는 인덱스입니다. 위의 예를 설명하면

- x.shape 은 (2, 2) 입니다.
- tf.reduce_mean(x, axis=0) 은
- x.shape[axis]: x.shape[0] 에 대하여 연산을 하라는 의미
입니다.

X.shape == (5, 3, 2) 인 경우를 생각해봅시다. 이 경우 tf.reduce_mean(X, axis=1) 의 결과값은

1. X.shape[axis] => X.shape[1] 에 대해서 연산을 하기 때문에
2. tf.reduce_mean(X, axis=1).shape 은 (5, 3, 2) -> (5, 2) 가 됩니다.

In [54]:
print(tf.reduce_sum(x))
print(tf.reduce_sum(x, axis=0))
print(tf.reduce_sum(x, axis=-1))
print(tf.reduce_mean(tf.reduce_sum(x, axis=-1)))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([4. 6.], shape=(2,), dtype=float32)
tf.Tensor([3. 7.], shape=(2,), dtype=float32)
tf.Tensor(5.0, shape=(), dtype=float32)


## argmax

In [46]:
x = [[0, 1, 2],
     [2, 1, 0]]
print(tf.argmax(x, axis=0))
print(tf.argmax(x, axis=1))
print(tf.argmax(x, axis=-1))

tf.Tensor([1 0 0], shape=(3,), dtype=int64)
tf.Tensor([2 0], shape=(2,), dtype=int64)
tf.Tensor([2 0], shape=(2,), dtype=int64)


## reshape

In [3]:
print("********** Reshape ****************")
# reshape

t = tf.constant([[[0, 1, 2],
               [3, 4, 5]], 
              [[6, 7, 8],
               [9, 10, 11]]])

print(tf.shape(t))

print(tf.reshape(t, shape=[-1]))
print(tf.reshape(t, shape=[-1, 2]))
print(tf.reshape(t, shape=[-1, 3]))
print(tf.reshape(t, shape=[-1, 1, 3]))

********** Reshape ****************
tf.Tensor([2 2 3], shape=(3,), dtype=int32)
tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11], shape=(12,), dtype=int32)
tf.Tensor(
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]], shape=(6, 2), dtype=int32)
tf.Tensor(
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[[ 0  1  2]]

 [[ 3  4  5]]

 [[ 6  7  8]]

 [[ 9 10 11]]], shape=(4, 1, 3), dtype=int32)


## squeeze and expand_dims

In [36]:
print(tf.squeeze([[0], [1], [2]]))
print(tf.expand_dims([0, 1, 2], 1))

tf.Tensor([0 1 2], shape=(3,), dtype=int32)
tf.Tensor(
[[0]
 [1]
 [2]], shape=(3, 1), dtype=int32)


## one-hot encoding

In [47]:
print("********** One hot ****************")
label = tf.constant([0, 1, 2, 0])
onehot1 = tf.one_hot(label, depth=3)
onehot2 = keras.utils.to_categorical(label, num_classes=3)

print(onehot1, type(onehot1))
print(onehot2, type(onehot2))

********** One hot ****************
tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]], shape=(4, 3), dtype=float32) <class 'tensorflow.python.framework.ops.EagerTensor'>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]] <class 'numpy.ndarray'>


## type casting

In [49]:
print("********** Casting ****************")

print(tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32))
print(tf.cast([True, False, 1 == 1, 0 == 1], tf.int32))

********** Casting ****************
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([1 0 1 0], shape=(4,), dtype=int32)


## stack

In [50]:
print("********** Stack ****************")

x = [1, 4]
y = [2, 5]
z = [3, 6]

print(tf.stack([x, y, z]))

********** Stack ****************
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


## Ones and Zeros like

In [22]:
print("********** Ones and Zeros like ****************")

x = [[0, 1, 2],
     [2, 1, 0]]

print(tf.ones_like(x)) # 1로 채운
print(tf.zeros_like(x)) # 0으로 채운

********** Ones and Zeros like ****************
tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)



## zips

In [51]:
print("********** Zips ****************")

for x, y in zip([1, 2, 3], [4, 5, 6]): # x와 y에 담아서 처리
  print(x, y)


********** Zips ****************
1 4
2 5
3 6
