### TensorFlow를 이용하여 자동미분 계산하기
1. Deep learning model을 학습시키기 위해서는 gradient descent 방법을 사용하고, 이를 위해서는 gradient 즉 미분을 계산해야 합니다. (Loss 를 weight로 미분)
2. TensorFlow에서 자동으로 미분을 계산하는 방법을 알아보겠습니다
3. TensorFlow는 자동 미분을 위한 tf.GradientTape API를 제공합니다.

In [3]:
import tensorflow as tf

### z = f(w1, w2) = 3*W1^2 + 2*W1*W2 함수 정의

In [4]:
def f(w1, w2):
    return 3*w1**2 + 2*w1*w2

### w1 = 5., w2 = 3. 할당
### tf.GradientTape는 컨텍스트(context) 안에서 실행된 모든 연산을 테이프(tape)에 "기록"합니다.

In [5]:
w1, w2 = tf.Variable(5.), tf.Variable(3.)
with tf.GradientTape() as tape:
    z = f(w1, w2)

### 그 다음 TensorFlow는 후진 방식 자동 미분(reverse mode differentiation)을 사용해 테이프에 "기록된" 연산의 그래디언트를 계산합니다.

In [29]:
gradients = tape.gradient(z, [w1, w2])
print(gradients)

[<tf.Tensor: id=293, shape=(), dtype=float32, numpy=36.0>, <tf.Tensor: id=285, shape=(), dtype=float32, numpy=10.0>]


### GradientTape를 열게되면, 그때부턴 tape.watch()를 통해 tensor를 확인하고, 이 tensor를 입력으로써 사용하는 미분을 자동으로 계산하는것이 가능합니다.

In [30]:
c1, c2 = tf.constant(5.), tf.constant(3.)
with tf.GradientTape() as tape:
    tape.watch(c1)
    tape.watch(c2)
    z = f(c1, c2)

### c1, c2에 대한 미분 계산

In [31]:
gradients = tape.gradient(z, [c1, c2])
print(gradients)

[<tf.Tensor: id=316, shape=(), dtype=float32, numpy=36.0>, <tf.Tensor: id=308, shape=(), dtype=float32, numpy=10.0>]


In [32]:
x = tf.ones((2, 2))
print(x)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [33]:
with tf.GradientTape() as t:
    t.watch(x)    
    y = tf.reduce_sum(x)
    z = tf.multiply(y, y)

In [34]:
dz_dx = t.gradient(z, x)
print(dz_dx)

tf.Tensor(
[[8. 8.]
 [8. 8.]], shape=(2, 2), dtype=float32)


In [35]:
x = tf.Variable(x)
with tf.GradientTape() as t:   
    y = tf.reduce_sum(x)
    z = tf.multiply(y, y)

In [36]:
dz_dx = t.gradient(z, x)
print(dz_dx)

tf.Tensor(
[[8. 8.]
 [8. 8.]], shape=(2, 2), dtype=float32)
